"use client";

import { useEffect, useState } from "react";

/**
 * Registers the service worker that makes the game installable and playable
 * offline, and offers a reload when a newer build has been cached.
 *
 * The worker is only generated by `next build` (see scripts/build-sw.mjs), so
 * in `next dev` there is nothing to register — but a worker installed by an
 * earlier `npm start` has to be cleared away, or it goes on serving that build
 * over the dev server. See below.
 */
// Set once per tab so the reload below cannot become a loop.
const RELOADED = "whot-dev-sw-cleared";

async function clearDevWorkers() {
  const registrations = await navigator.serviceWorker.getRegistrations();
  // The page keeps its current controller until it is reloaded, so a
  // controlled page is stale even after the worker is unregistered.
  const controlled = navigator.serviceWorker.controller !== null;
  if (registrations.length === 0 && !controlled) return;

  await Promise.all(registrations.map((r) => r.unregister()));
  const names = await caches.keys();
  await Promise.all(names.map((name) => caches.delete(name)));

  if (!controlled) return;
  try {
    if (sessionStorage.getItem(RELOADED)) return;
    sessionStorage.setItem(RELOADED, "1");
  } catch {
    // Storage is blocked, so the loop guard is gone with it — better to leave
    // the page stale than to reload it over and over.
    return;
  }
  window.location.reload();
}

export default function ServiceWorkerRegistrar() {
  const [waiting, setWaiting] = useState<ServiceWorker | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    if (!("serviceWorker" in navigator)) return;
    // Service workers need a secure context: https, or localhost while testing.
    if (!window.isSecureContext) return;

    // scripts/serve.mjs serves the production build on http://localhost:3000,
    // which is the origin `next dev` uses too — so a worker installed by
    // `npm start` stays active and intercepts the dev server's requests. Its
    // fetch handler is cache-first for everything that is not a navigation,
    // /_next chunks and RSC payloads included, so it hands the page pieces of
    // a stale build and hydration fails on the mismatch. Nothing here needs a
    // worker in dev, so take it out of the way rather than work around it.
    if (process.env.NODE_ENV !== "production") {
      void clearDevWorkers();
      return;
    }

    let cancelled = false;

    navigator.serviceWorker
      .register("/sw.js", { scope: "/", updateViaCache: "none" })
      .then((registration) => {
        if (cancelled) return;

        // A build newer than the running one is already sitting in the wings.
        if (registration.waiting && navigator.serviceWorker.controller) {
          setWaiting(registration.waiting);
        }

        registration.addEventListener("updatefound", () => {
          const installing = registration.installing;
          if (!installing) return;
          installing.addEventListener("statechange", () => {
            // "installed" with an existing controller means an update, not a
            // first install — only then is a reload worth offering.
            if (
              installing.state === "installed" &&
              navigator.serviceWorker.controller
            ) {
              setWaiting(installing);
            }
          });
        });
      })
      .catch(() => {
        // An unregistered worker just means no offline play; the game itself
        // is unaffected, so there is nothing to report to the player.
      });

    // The new worker calls skipWaiting, then takes over; reload onto it once.
    let reloading = false;
    const onControllerChange = () => {
      if (reloading) return;
      reloading = true;
      window.location.reload();
    };
    navigator.serviceWorker.addEventListener(
      "controllerchange",
      onControllerChange,
    );

    return () => {
      cancelled = true;
      navigator.serviceWorker.removeEventListener(
        "controllerchange",
        onControllerChange,
      );
    };
  }, []);

  if (!waiting) return null;

  return (
    <div className="pointer-events-auto fixed inset-x-0 bottom-0 z-70 flex justify-center p-3 pb-[calc(0.75rem+env(safe-area-inset-bottom))]">
      <div className="flex items-center gap-3 rounded-xl border border-amber-400/60 bg-emerald-900/95 px-4 py-2 text-sm text-white shadow-2xl">
        <span className="font-semibold">A new version is ready.</span>
        <button
          type="button"
          onClick={() => waiting.postMessage({ type: "SKIP_WAITING" })}
          className="rounded-lg bg-amber-400 px-3 py-1 font-bold text-emerald-950 transition hover:bg-amber-300"
        >
          Update
        </button>
        <button
          type="button"
          onClick={() => setWaiting(null)}
          aria-label="Dismiss"
          className="rounded-lg border border-white/20 px-2 py-1 font-semibold transition hover:bg-white/10"
        >
          Later
        </button>
      </div>
    </div>
  );
}
