"use client";

import { useEffect, useState } from "react";

/**
 * Registers the service worker that makes the game installable and playable
 * offline, and offers a reload when a newer build has been cached.
 *
 * The worker is only generated by `next build` (see scripts/build-sw.mjs), so
 * in `next dev` the registration simply finds nothing and does nothing.
 */
export default function ServiceWorkerRegistrar() {
  const [waiting, setWaiting] = useState<ServiceWorker | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    if (!("serviceWorker" in navigator)) return;
    // Service workers need a secure context: https, or localhost while testing.
    if (!window.isSecureContext) return;

    let cancelled = false;

    navigator.serviceWorker
      .register("/sw.js", { scope: "/", updateViaCache: "none" })
      .then((registration) => {
        if (cancelled) return;

        // A build newer than the running one is already sitting in the wings.
        if (registration.waiting && navigator.serviceWorker.controller) {
          setWaiting(registration.waiting);
        }

        registration.addEventListener("updatefound", () => {
          const installing = registration.installing;
          if (!installing) return;
          installing.addEventListener("statechange", () => {
            // "installed" with an existing controller means an update, not a
            // first install — only then is a reload worth offering.
            if (
              installing.state === "installed" &&
              navigator.serviceWorker.controller
            ) {
              setWaiting(installing);
            }
          });
        });
      })
      .catch(() => {
        // An unregistered worker just means no offline play; the game itself
        // is unaffected, so there is nothing to report to the player.
      });

    // The new worker calls skipWaiting, then takes over; reload onto it once.
    let reloading = false;
    const onControllerChange = () => {
      if (reloading) return;
      reloading = true;
      window.location.reload();
    };
    navigator.serviceWorker.addEventListener(
      "controllerchange",
      onControllerChange,
    );

    return () => {
      cancelled = true;
      navigator.serviceWorker.removeEventListener(
        "controllerchange",
        onControllerChange,
      );
    };
  }, []);

  if (!waiting) return null;

  return (
    <div className="pointer-events-auto fixed inset-x-0 bottom-0 z-70 flex justify-center p-3 pb-[calc(0.75rem+env(safe-area-inset-bottom))]">
      <div className="flex items-center gap-3 rounded-xl border border-amber-400/60 bg-emerald-900/95 px-4 py-2 text-sm text-white shadow-2xl">
        <span className="font-semibold">A new version is ready.</span>
        <button
          type="button"
          onClick={() => waiting.postMessage({ type: "SKIP_WAITING" })}
          className="rounded-lg bg-amber-400 px-3 py-1 font-bold text-emerald-950 transition hover:bg-amber-300"
        >
          Update
        </button>
        <button
          type="button"
          onClick={() => setWaiting(null)}
          aria-label="Dismiss"
          className="rounded-lg border border-white/20 px-2 py-1 font-semibold transition hover:bg-white/10"
        >
          Later
        </button>
      </div>
    </div>
  );
}
