/**
 * Generates out/sw.js after `next build`.
 *
 * The precache list is read from the actual build output, so hashed chunk
 * filenames are always correct and every asset the game needs — HTML, JS, CSS,
 * fonts, board images and the sound effects — is stored on install. That is
 * what makes the installed app playable with no connection at all.
 */
import { createHash } from "node:crypto";
import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const OUT = path.join(ROOT, "out");

// Build artefacts that must never be fetched from cache, or are pointless to
// precache (source maps are only read by devtools).
const SKIP = new Set(["sw.js"]);
const SKIP_EXT = new Set([".map"]);

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(full)));
    } else {
      files.push(full);
    }
  }
  return files;
}

try {
  await stat(OUT);
} catch {
  console.error(
    "[build-sw] out/ not found. Run `next build` first (npm run build does both).",
  );
  process.exit(1);
}

const files = await walk(OUT);
const hash = createHash("sha256");
const urls = [];

for (const file of files.sort()) {
  const rel = path.relative(OUT, file).split(path.sep).join("/");
  if (SKIP.has(rel)) continue;
  if (SKIP_EXT.has(path.extname(rel))) continue;

  // "/index.html" is reachable as "/", which is what start_url requests.
  urls.push(rel === "index.html" ? "/" : "/" + rel);
  hash.update(rel);
  hash.update(await readFile(file));
}

// The cache name changes whenever any asset changes, which is what triggers
// the update flow in ServiceWorkerRegistrar.
const version = hash.digest("hex").slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs — do not edit by hand.
const CACHE = "whot-v${version}";
const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // addAll is atomic: one bad response and nothing is cached, leaving the
      // previous worker in charge. Add individually so a single missing asset
      // cannot break the whole install.
      await Promise.all(
        PRECACHE.map((url) =>
          cache.add(new Request(url, { cache: "reload" })).catch(() => {}),
        ),
      );
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names.filter((n) => n !== CACHE).map((n) => caches.delete(n)),
      );
      await self.clients.claim();
    })(),
  );
});

// The page sends this when the player accepts the update banner.
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  // Only this origin is ours to serve; anything else goes straight to network.
  if (url.origin !== self.location.origin) return;

  // Navigations: serve the cached app shell so a cold launch works offline.
  if (request.mode === "navigate") {
    event.respondWith(
      (async () => {
        try {
          return await fetch(request);
        } catch {
          const cache = await caches.open(CACHE);
          return (
            (await cache.match("/")) ||
            (await cache.match("/index.html")) ||
            Response.error()
          );
        }
      })(),
    );
    return;
  }

  // Everything else: cache first. Every precached asset is content-hashed or
  // static, so a hit is always safe to serve.
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(request, { ignoreSearch: false });
      if (hit) return hit;
      try {
        const response = await fetch(request);
        // Stash same-origin successes so assets fetched lazily (a sound played
        // for the first time) are there next time, offline.
        if (response.ok && response.type === "basic") {
          cache.put(request, response.clone());
        }
        return response;
      } catch {
        return Response.error();
      }
    })(),
  );
});
`;

await writeFile(path.join(OUT, "sw.js"), sw);
console.log(
  `[build-sw] wrote out/sw.js — cache whot-v${version}, ${urls.length} assets precached`,
);
